name: Analysis
on: [push, pull_request]
permissions:
  contents: read

jobs:
  static_analysis:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'

    - name: Install static analysis tools
      run: |
        go install golang.org/x/vuln/cmd/govulncheck@latest
        go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
        go install honnef.co/go/tools/cmd/staticcheck@latest
        go install mvdan.cc/gofumpt@latest

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends clang libgl1-mesa-dev libegl1-mesa-dev libgles2-mesa-dev libx11-dev xorg-dev

    - name: Vet
      run: go vet ./...

    - name: Gofumpt
      run: test -z "$(gofumpt -d -e . | tee /dev/stderr)"

    - name: Gocyclo
      run: gocyclo -over 10 .

    - name: Staticcheck
      run: staticcheck ./...

    - name: Vulncheck
      run: govulncheck ./...
